http:
  routers:
    mealie:
      rule: Host(`mealie.example.com`)
      entrypoints:
      - websecure
      service: mealie
    mealie-local:
      rule: Host(`mealie.local`)
      entrypoints:
      - web
      service: mealie
    uptime:
      rule: Host(`uptime.example.com`)
      entrypoints:
      - websecure
      service: uptime
    uptime-local:
      rule: Host(`uptime.local`)
      entrypoints:
      - web
      service: uptime
  services:
    mealie:
      loadbalancer:
        servers:
        - url: http://192.168.1.11:9925
    uptime:
      loadbalancer:
        servers:
        - url: http://192.168.1.11:3001
